Day 3
Using a tutorial : https://www.youtube.com/watch?v=xV7S8BhIeBo

LESSON 6----
Goal: We want the active button class to be applied to the button the user has clicked on and remove all other elements from the active button class (We want the button the user has clicked on to turn green while all other buttons are greyed out)
1. Start with turning the active button green:
1a. In the scss file, above where we targeted the control class, target the active button class
1b. Set the background to the secondary color (green) and give it a transition
1c. Target the icon and make the icon's color white
1d. Success!!!

----check-point----

2. Create a new! javascript file named app
3. Select all of the elements in the section class (we already gave each of the individual sections the class section so we could easily reference them later for this javascript file)
4. Select all of the elements inside the controls class (the parent container for the individual buttons)
5. Select all of the elements inside the control class
6. Select the body name main-landing-page
7. Create a new function named PageTransitions
8. Comment for the goal of the PageTransitions function
9. Create a for loop, where i is set to 0 and we are going to iterate though all of the buttons (the length of SectionButton)
10. At the current index of SectionButton, we want to know if the mouse was clicked by adding an event listener
11. We want to store the active button as the current button
12. When another button is clicked (which what we're going for you know) we want to remove the active button class from the current button so we can add the active button class to the new button that was clicked.
13. Add the active button class to the button that was clicked using this function in javascript
14. Now that we created the functionality of the function let's call it so it runs
----success pending----

Error: It didn't do anything, the buttons do not have the functionality, only the main landing page is illuminated green and the buttons do not react to clicking

yikes